### PR TITLE
Fix for redmine 4.0

### PR DESCRIPTION
**Pull request by nayuta**
Fix for redmine 4.0. Test with Redmine 4.0.4.Stable and Auth0.

- [x] Fix code
- [x] `rake test`
- [x] Sign in
- [x] Sign out
- [x] Replace Redmine login page
- [x] Create users automatically?

Can anyone check to untested items?

### CODE REVIEW

**Comment by nayuta** [comment]
Related to #43 .

**Comment by nayuta** [comment]
I've tested it and "Replace Redmine login page" doesn't work.

I'll try to fix it after this weekend (:

**Comment by nayuta** [comment]
Hi, I've fix it. Could you check this? @chrodriguez

**Comment by chrodriguez** [comment]
Thanks a lot!

**Pull request merged**
